spring:
    application:
        name: tabnews-search-service
    profiles:
        active: tabnews_search
    config:
        import: configserver:http://localhost:8888
jasypt:
    encryptor:
        password: ${JASYPT_PASSWORD}
